name: Documentation

on:
  push:
    branches:
      - main
    tags: '*'
  pull_request:

concurrency:
  # Skip intermediate builds: always.
  # Cancel intermediate builds: only if it is a pull request build.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}

jobs:
  docs:
    name: Documentation
    runs-on: ubuntu-latest
    permissions:
      contents: write
      statuses: write
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@v1
        with:
          version: '1.11'
      - name: Configure doc environment
        shell: julia --project=docs --color=yes {0}
        run: |
          using Pkg
          # Only instantiate docs environment, don't develop main package
          Pkg.instantiate()
      - name: Build documentation
        shell: julia --project=docs --color=yes {0}
        run: |
          # Add main package path to LOAD_PATH for importing
          push!(LOAD_PATH, "../src")
          include("make.jl")
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 